/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbuseRouteImport } from './routes/abuse'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as LoveRouteImport } from './routes/love'
import { Route as NowRouteImport } from './routes/now'
import { Route as SkillRouteImport } from './routes/skill'
import { Route as SoulRouteImport } from './routes/soul'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbuseRoute = AbuseRouteImport.update({
  id: '/abuse',
  path: '/abuse',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoveRoute = LoveRouteImport.update({
  id: '/love',
  path: '/love',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillRoute = SkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulRoute = SoulRouteImport.update({
  id: '/soul',
  path: '/soul',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abuse': typeof AbuseRoute
  '/duel': typeof DuelRoute
  '/love': typeof LoveRoute
  '/now': typeof NowRoute
  '/skill': typeof SkillRoute
  '/soul': typeof SoulRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abuse': typeof AbuseRoute
  '/duel': typeof DuelRoute
  '/love': typeof LoveRoute
  '/now': typeof NowRoute
  '/skill': typeof SkillRoute
  '/soul': typeof SoulRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abuse': typeof AbuseRoute
  '/duel': typeof DuelRoute
  '/love': typeof LoveRoute
  '/now': typeof NowRoute
  '/skill': typeof SkillRoute
  '/soul': typeof SoulRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abuse' | '/duel' | '/love' | '/now' | '/skill' | '/soul'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abuse' | '/duel' | '/love' | '/now' | '/skill' | '/soul'
  id:
    | '__root__'
    | '/'
    | '/abuse'
    | '/duel'
    | '/love'
    | '/now'
    | '/skill'
    | '/soul'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbuseRoute: typeof AbuseRoute
  DuelRoute: typeof DuelRoute
  LoveRoute: typeof LoveRoute
  NowRoute: typeof NowRoute
  SkillRoute: typeof SkillRoute
  SoulRoute: typeof SoulRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abuse': {
      id: '/abuse'
      path: '/abuse'
      fullPath: '/abuse'
      preLoaderRoute: typeof AbuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/love': {
      id: '/love'
      path: '/love'
      fullPath: '/love'
      preLoaderRoute: typeof LoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill': {
      id: '/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof SkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soul': {
      id: '/soul'
      path: '/soul'
      fullPath: '/soul'
      preLoaderRoute: typeof SoulRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbuseRoute: AbuseRoute,
  DuelRoute: DuelRoute,
  LoveRoute: LoveRoute,
  NowRoute: NowRoute,
  SkillRoute: SkillRoute,
  SoulRoute: SoulRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
